#ifndef __APP_USB_HID_H
#define __APP_USB_HID_H

#include <zephyr.h>

#define HID_KBD_REP_FLAG_LEFT_CTRL   BIT(0)
#define HID_KBD_REP_FLAG_LEFT_SHIFT  BIT(1)
#define HID_KBD_REP_FLAG_LEFT_ALT    BIT(2)
#define HID_KBD_REP_FLAG_LEFT_GUI    BIT(3)
#define HID_KBD_REP_FLAG_RIGHT_CTRL  BIT(4)
#define HID_KBD_REP_FLAG_RIGHT_SHIFT BIT(5)
#define HID_KBD_REP_FLAG_RIGHT_ALT   BIT(6)
#define HID_KBD_REP_FLAG_RIGHT_GUI   BIT(7)

enum {KEY_A=0x4, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,
		KEY_1=0x1E, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, 
		KEY_ENTER=0x28, KEY_ESC, KEY_DELETE, KEY_TAB, KEY_SPACE, KEY_DASH, KEY_EQUAL, 
		KEY_F1=0x3A, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, 
		KEY_PRINTSCREEN=0x46, KEY_SCROLL_LOCK, KEY_PAUSE, KEY_INSERT, KEY_HOME, KEY_PAGE_UP, KEY_DEL_FORWARD, KEY_END, KEY_PAGE_DOWN, KEY_ARROW_RIGHT, KEY_ARROW_LEFT, KEY_ARROW_DOWN, KEY_ARROW_UP,
		KEY_KPAD_NUM_LOCK=0x53, KEY_KPAD_DIVIDE, KEY_KPAD_MULTIPLY, KEY_KPAD_MINUS, KEY_KPAD_PLUS, KEY_KPAD_ENTER, KEY_KPAD_1, KEY_KPAD_2, KEY_KPAD_3, KEY_KPAD_4, KEY_KPAD_5, KEY_KPAD_6, KEY_KPAD_7, KEY_KPAD_8, KEY_KPAD_9, KEY_KPAD_0, KEY_KPAD_DOT};

int app_usb_hid_init(void);

int app_usb_hid_send_kbd_packet(uint8_t key1, uint8_t flags);

int app_usb_hid_send_cons_ctrl_packet(uint8_t cons_ctrl_bitfield);

#endif
